source 'https://rubygems.org'

gem 'google-adwords-api'
gem "rails"
gem "sqlite3"

gem "rspec-rails"

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# ENV variables
gem 'figaro'
